### ISSUE TITLE
Ability to run on t2.micro with single thread

### ISSUE THREAD

**Issue by ramses999** [aws-samples/multi-account-security-assessment-via-prowler#32]
Thanks for the project, it really simplifies the wiring around the prowler, but I have a need to save a lot of money, so please add the following feature:
**Launching prowler on Instance type "t2.micro" with single-threaded scanning of each listed account.**

Let it be better slowly, but then I will not worry about the money.

**Comment by micvirgi** [comment]
I just saw this issue yesterday.  I tested PARALLELISM=1 with t2.micro. (prowler_scan.sh script)
This use case revealed that I had to resolve an issue with the queue mechanism monitoring for the completion of a single thread.
Once that was resolve, I tested with t2.micro in my lab.  

t2.micro does not natively have enough memory to sustain this process and the inclusion of disk based swap space allowed the process to complete in my lab with very few resources (VERY VERY slowly).  
Depending on your environment and the number of resources being analyzed, it's possible that the Prowler process will fail due to memory needs, but you'll need to test this.

I did not add in t2.micro as a AllowedValue for InstanceType in the Prowler-resources.yaml template, however you could easily modify the template for your needs prior to deployment.

The code does support parallelism set to 1 now.
